#!/bin/bash

UM_DIR=~/um
SOURCES_DIR=$UM_DIR/sources

DATA_DIR=$UM_DIR/.data
WORKSPACE_DIR=$UM_DIR/workspaces

INTO_FILE=$DATA_DIR/into.sh

makeDirIfNonExistant() {
	echo 'Creating if not already exists: ' $1
	if [ ! -d "$1" ]; then
		mkdir $1
	fi
}


echo "                  UM installed                  "
echo "Going to be running a post installation script  "
echo "................................................"
echo
echo "            Creating the main UM file           "
echo "   Here will store all the files you add to UM  "
echo "          As well as some shell scripts         "


makeDirIfNonExistant $UM_DIR
makeDirIfNonExistant $SOURCES_DIR
makeDirIfNonExistant $DATA_DIR
makeDirIfNonExistant $WORKSPACE_DIR

touch $INTO_FILE
chmod +x $INTO_FILE

echo
echo
echo "Awesome! You must now add the following to your .bash_profile, .zprofile, .zshrc, etc:"
echo "                          . <(umm completion)                                     "
echo
echo
